### PR TITLE
chore: update sourceror to 1.0

### PR DESCRIPTION
**Pull request by linusdm**
update sourceror to 1.0

also requires an update of rewrite to at least 0.10.1

### CODE REVIEW

**Comment by linusdm** [comment]
In an attempt to add ash (3.0.0-rc) to an existing project, I bumped into the issue that this was incompatible with our existing dependency on mneme, due to the common dependency on sourceror.

Sourceror seems to be released as stable (1.0) a few months ago, without any breaking changes. The tests still run with the specified Elixir and Erlang versions in `.tool-versions`. No breaking changes were published for the rewrite package either (last breaking change was integrated [here](https://github.com/zachallaun/mneme/pull/47)), so this seems like an easy update.

**Comment by zachallaun** [comment]
Hi @linusdm! Thanks for doing the legwork here. I'll be able to look at this over the weekend and will prioritize getting a release out. :)

**Comment by zachallaun** [comment]
❤️

**Comment by zachallaun** [comment]
@linusdm Released v0.5.1. Thanks again for bringing this up!

**Pull request merged**
