### PR TITLE
Update rewrite to 1.0.0

### PR DESCRIPTION
**Pull request by NickNeck**
Hi @zachallaun 

I have released a new version of `rewrite` and it comes with a bunch of breaking changes and a better handling of source formatting.

This PR contains all the changes needed for `meneme`:

- The rewrite project now gets a `%DotFormatter{}` to format the code.
- The `resync_quoted: false` prevents the AST from being changed when the source is updated with `:quoted`. I think this makes the `Source.put_private(:patched_ast, ast)` obsolete.
- The `TextDiff` module has been moved to its own package.

For now we have a little conflict with `igniter` and for that we need `{:rewrite, "~> 1.0", override: true}`. The `override: true` can be removed once `igniter` also uses `rewrite` 1.0.0. A PR (https://github.com/ash-project/igniter/pull/135) is already ~~created~~ merged in the `igniter` repo.

Have a nice weekend.

### CODE REVIEW

**Comment by zachallaun** [comment]
Thank you so much for doing the legwork on this!

It looks like the Igniter PR has already been merged, so I'll wait until that's out in a release and then upgrade that to solve for the override workaround.

**Comment by zachallaun** [comment]
@NickNeck If you don't mind, do you have a moment to take a look at this when you bump Rewrite to 1.0.1? With that version, the PR as it is now fails to format locals_without_parens in the integration tests. I know there were some changes to that and thought you might know off-hand what's going on. :)

**Comment by NickNeck** [comment]
I will take a look.

**Comment by zachallaun** [comment]
Thank you for updating this! Will get it merged shortly :)

**Pull request merged**
